// 더미 채팅 데이터
export const dummyData = {
  totalCount: 21,
  nodes: [
    {
      id: 1,
      chatRoomId: 1,
      userId: "me",
      content: "안녕",
      attachment: {
        id: 1,
        type: "string",
        url: "string",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
    {
      id: 2,
      chatRoomId: 1,
      userId: null,
      content: "클레오파트라",
      attachment: {
        id: 2,
        type: "string",
        url: "string",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
    {
      id: 3,
      chatRoomId: 1,
      userId: "me",
      content: "세상에서 제일 가는",
      attachment: {
        id: 3,
        type: "string",
        url: "string",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
    {
      id: 4,
      chatRoomId: 1,
      userId: null,
      content: "포테이토칩",
      attachment: {
        id: 4,
        type: "string",
        url: "string",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
    {
      id: 5,
      chatRoomId: 1,
      userId: "me",
      content: "안녕",
      attachment: {
        id: 5,
        type: "string",
        url: "string",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },

    {
      id: 6,
      chatRoomId: 1,
      userId: "me",
      content: "안녕",
      attachment: {
        id: 6,
        type: "string",
        url: "string",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
    {
      id: 7,
      chatRoomId: 1,
      userId: null,
      content: "클레오파트라",
      attachment: {
        id: 7,
        type: "string",
        url: "string",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
    {
      id: 8,
      chatRoomId: 1,
      userId: "me",
      content: "세상에서 제일 가는",
      attachment: {
        id: 8,
        type: "string",
        url: "string",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
    {
      id: 9,
      chatRoomId: 1,
      userId: null,
      content: "포테이토칩",
      attachment: {
        id: 9,
        type: "string",
        url: "string",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
  ],
};
